version: "3"

services:
  app:
    container_name: garimpei_auth
    image: garimpei/auth
    build: .
    volumes:
      - ".:/code/"
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - NODE_ENV=DEVELOPMENT
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_DB=garimpei_auth
      - DATABASE_PORT=5432

  postgres:
    image: postgres:latest
    container_name: garimpei_auth_db
    ports:
      - "5432:5432"
    volumes:
      - ./.ignore/postgres/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=garimpei_auth

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "garimpei@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "garimpei123!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
